---
title: "CISProject"
authors: Levi Rosendall & Joey Ferkull
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gifski)
library(urbnmapr)
library(gganimate)
library(sf)
library(transformr)
library(lubridate)
Plotting <- read_csv(here::here('~/CIS661/CIS661CitiBike/WITHCONT (1).csv'))#read_csv(here::here('~/CIS661/CIS661CitiBike/WITHCONT.csv'))
Plotting <- Plotting %>% 
  mutate(actualTime = dmy_hms(time))
SampleData <- Plotting %>% 
  filter(day(actualTime)==1) %>% 
  mutate(CharCont = ifelse(contamination==1, "C",
                           ifelse(contamination==0, "N", "no"))) %>% 
  mutate(minute=minute(actualTime)) %>% 
  mutate(hour=hour(actualTime)) %>% 
  arrange(hour, minute) %>% 
  mutate(plotTime=100*hour+minute)
```



```{r}
library(plotly)
library(gapminder)
p <- SampleData %>%
  filter(plotTime<200) %>% 
  plot_ly(
    x = ~latitude, 
    y = ~longitude,
    color = ~CharCont, 
    frame = ~plotTime, 
    text = ~bikeid, 
    hoverinfo = "bikeid",
    type = 'scatter',
    mode = 'markers'
  ) %>%
  layout(
    xaxis = list(
      type = "log"
    )
  )
p
#try fifteen minute increments, plot where bike is
#just plot contaminated over days

```

```{r dailyData}
library(plotly)
newPlotting <- Plotting %>% 
  filter(contamination==1) %>% 
  group_by(station_name, dayNum=day(dmy_hms(time))) %>% 
  arrange(station_name, dayNum) %>% 
  mutate(dailyCont=sum(contamination)) %>% 
  select(-time, -bikeid, -actualTime) %>% 
  distinct()

plotTable <- newPlotting %>% 
  group_by(station_name) %>% 
  mutate(cont=cumsum(dailyCont)) %>% 
  ungroup()

plotTable <- plotTable %>% 
  filter(station_name!="NULL") 

plotTableLastDay <- plotTable%>% 
  filter(dayNum==30)
```


```{r}
library(leaflet)

# define bounding box with longitude/latitude coordinates
bbox <- list(
  p1 = list(long = -74.02, lat = 40.6),
  p2 = list(long = -73.94, lat = 40.78)
)

nycimage <- leaflet() %>%
  addTiles() %>% 
  addRectangles(
    lng1 = bbox$p1$long, lat1 = bbox$p1$lat,
    lng2 = bbox$p2$long, lat2 = bbox$p2$lat,
    fillColor = "transparent"
  ) %>%
  fitBounds(
    lng1 = bbox$p1$long, lat1 = bbox$p1$lat,
    lng2 = bbox$p2$long, lat2 = bbox$p2$lat,
  )

define_image_size <- function(bbox, major_dim = 400) {
  # calculate aspect ration (width/height) from lat/long bounding box
  aspect_ratio <- abs((bbox$p1$long - bbox$p2$long) / (bbox$p1$lat - bbox$p2$lat))
  # define dimensions
  img_width <- ifelse(aspect_ratio > 1, major_dim, major_dim*aspect_ratio) %>% round()
  img_height <- ifelse(aspect_ratio < 1, major_dim, major_dim/aspect_ratio) %>% round()
  size_str <- paste(img_width, img_height, sep = ",")
  list(height = img_height, width = img_width, size = size_str)
}


image_size <- define_image_size(bbox, major_dim = 600)
image_size
library(devtools)
library(htmlwidgets)
library(mapview)
webshot::install_phantomjs()
mapshot(nycimage, file = "~/CIS661/CIS661CitiBike/nycimage.png")
```


```{r}
library(png)

img <- readPNG("~/CIS661/CIS661CitiBike/nycimage.png") 

h<-dim(img)[1] # image height
w<-dim(img)[2] # image width

library(rayshader)
mtplot = ggplot(plotTableLastDay) +
  geom_point(aes(x = latitude, y = longitude, color = cont)) +
  scale_color_continuous(limits = c(0, 120))
mtplot

par(mfrow = c(1, 2))
plot_gg(mtplot, width = 3.5, raytrace = FALSE, preview = TRUE)

plot_gg(mtplot, width = 3.5, multicore = TRUE, windowsize = c(800, 800),
        zoom = 0.85, phi = 35, theta = 30, sunangle = 225, soliddepth = -100)

render_snapshot(clear = TRUE)


```


```{r cleanOneStation}
#cleaning W 20 St & 11 Ave
cleanOnePlotting <- Plotting %>%
  arrange(bikeid, time) %>% 
  group_by(bikeid) %>% 
  mutate(numEntries=ave(bikeid/bikeid, FUN=cumsum)) %>% 
  mutate(contFlag=contamination) %>% 
  mutate(contFlag=ifelse(station_name=="W 20 St & 11 Ave", 10, contFlag)) %>% 
  mutate(isCleaned=cumsum(contFlag))
  
cleanOnePlotting <- cleanOnePlotting %>% 
  mutate(contamination=ifelse(isCleaned>numEntries, 0, contamination))
```

```{r cleanOneLastDay}
library(plotly)
newCleanOnePlotting <- cleanOnePlotting %>% 
  filter(contamination==1) %>% 
  group_by(station_name, dayNum=day(dmy_hms(time))) %>% 
  arrange(station_name, dayNum) %>% 
  mutate(dailyCont=sum(contamination)) %>% 
  select(-time, -bikeid, -actualTime, -numEntries, -contamination, -isCleaned) %>% 
  distinct()

cleanOnePlotTable <- newCleanOnePlotting %>% 
  group_by(station_name) %>% 
  mutate(cont=cumsum(dailyCont)) %>% 
  ungroup()

cleanOnePlotTable <- cleanOnePlotTable %>% 
  filter(station_name!="NULL") 

cleanOnePlotTableLastDay <- cleanOnePlotTable%>% 
  filter(dayNum==30)

```


```{r}
mtplotcleanone = ggplot(cleanOnePlotTableLastDay) +
  geom_point(aes(x = latitude, y = longitude, color = cont)) +
  scale_color_continuous(limits = c(0, 120))
mtplotcleanone

par(mfrow = c(1, 2))
plot_gg(mtplotcleanone, width = 3.5, raytrace = FALSE, preview = TRUE)

plot_gg(mtplotcleanone, width = 3.5, multicore = TRUE, windowsize = c(800, 800),
        zoom = 0.85, phi = 35, theta = 30, sunangle = 225, soliddepth = -100)

render_snapshot(clear = TRUE)
```



